# Uncomment the next line to define a global platform for your project
platform :ios, '10.3'

target 'Medssenger' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Storage'
pod ‘MessageKit’
pod ’SwiftKeychainWrapper’
pod 'SVProgressHUD'
pod 'SDWebImage/WebP'
#pod 'TextFieldEffects'



  # Pods for Medssenger

end
